#!/bin/bash

for kver in /lib/modules/linux-headers-*; do
    [ -d "$kver" ] || continue
    cd /usr/src/"$kver";
    echo "Compiling headers - please wait ...";
    find /usr/src/"$kver" -type f -exec touch {} +
    make CC=gcc CONFIG_RDK_MOD=y scripts
done

exit 0

